# Generated by Django 4.2.5 on 2023-09-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcard',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
