# Generated by Django 4.2.5 on 2023-09-25 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_text',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='timestamp',
        ),
    ]
